package Interface;

import Networking.Client.ConnectionHandler;
import Console.ConsoleFrame;
import Networking.Requests.BooleanResponse;
import Networking.Requests.LoginAccount;
import Networking.Requests.RegisterAccount;
import Networking.Server.Player;
import Security.Guard;
import java.io.IOException;
import java.util.concurrent.ExecutionException;
import javax.swing.SwingWorker;

/**
 *
 * @author Dragos-Alexandru
 */
public class MultiplayerLoginRegisterPanel extends javax.swing.JPanel {

    private final MainFrame rootFrame;

    /**
     * Creates new form MultiplayerLoginPanel
     *
     * @param rootFrame
     */
    public MultiplayerLoginRegisterPanel(MainFrame rootFrame) {

        this.rootFrame = rootFrame;

        initComponents();
        this.usernameField.setText(Player.getInstance().getUsername());
        passwordField.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName(""); // NOI18N

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        username.setText("Username:");

        password.setText("Password:");

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username)
                    .addComponent(password))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordField)
                            .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(188, 188, 188))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        rootFrame.changePanel(new MultiplayerChooserPanel(rootFrame));
    }//GEN-LAST:event_backButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        LoginWorker worker = new LoginWorker();
        try {
            worker.execute();
            if (worker.get()) {
                String scrambledPassword
                        = Guard.scramblePassword(new String(passwordField.getPassword()));
                // Send a login request
                LoginAccount request
                        = new LoginAccount(usernameField.getText(), scrambledPassword);
                Object ob = ConnectionHandler.getInstance().readFromMasterServer(request);
                BooleanResponse response = (BooleanResponse) ob;
                // Check if the authentification was successful
                if (response.getValue() == false) {
                    ConsoleFrame.showError("No account matches the provided username and password");
                    return;
                }
                Player.getInstance().logIn(usernameField.getText());
                rootFrame.changePanel(new MultiplayerServerPanel(rootFrame));
            } else {
                ConsoleFrame.showError("Username can't contain these characters: ' = + ; \" ");
            }
        } catch (InterruptedException | ExecutionException | IOException | ClassNotFoundException ex) {
            ConsoleFrame.showError(ex.getMessage());
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        LoginWorker worker = new LoginWorker();
        try {
            worker.execute();
            if (worker.get()) {
                // Send a register request
                String scrambledPassword
                        = Guard.scramblePassword(new String(passwordField.getPassword()));
                RegisterAccount request
                        = new RegisterAccount(usernameField.getText(), scrambledPassword);
                Object ob = ConnectionHandler.getInstance().readFromMasterServer(request);
                BooleanResponse response = (BooleanResponse) ob;
                // Check if the authentification was successful
                if (response.getValue() == false) {
                    ConsoleFrame.showError("An account with that name already exists.");
                    return;
                }
                Player.getInstance().logIn(usernameField.getText());
                rootFrame.changePanel(new MultiplayerServerPanel(rootFrame));
            } else {
                ConsoleFrame.showError("Username can't contain these characters: ' = + ; \" ");
            }
        } catch (InterruptedException | ExecutionException | IOException | ClassNotFoundException ex) {
            ConsoleFrame.showError(ex.getMessage());
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private class LoginWorker extends SwingWorker<Boolean, Object> {

        @Override
        protected Boolean doInBackground() throws Exception {
            //This should start false
            boolean success;
            String username = usernameField.getText();
            String password = Guard.scramblePassword(String.valueOf(passwordField.getPassword()));

            success = checkUsername(username);

            return success;
        }

        private boolean checkUsername(String username) {
            char[] unacceptebleChars = {'\'', '=', '+', ';', '\"'};
            for (char c : unacceptebleChars) {
                if (username.indexOf(c) >= 0) {
                    return false;
                }
            }
            return true;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
