package Interface;

import Console.ConsoleFrame;
import Constants.VisualConstants;
import Source.Source;
import Source.SourceManager;
import Enums.GameModes;
import Visual.VisualEngine;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author Dragos-Alexandru
 */
public class SingleplayerPanel extends JPanel {

    private final MainFrame rootFrame;

    private final List<Source> sourceList;
    private final List<Source> addedSourceList = new ArrayList<>();
    private final DefaultListModel listModel = new DefaultListModel();
    private final DefaultListModel addedListModel = new DefaultListModel();

    /**
     * Creates new form SingleplayerPanel
     *
     * @param rootFrame
     */
    public SingleplayerPanel(MainFrame rootFrame) {

        this.rootFrame = rootFrame;
        initComponents();
        sourceList = SourceManager.getInstance().getSourceList();
        for (Source source : sourceList) {
            listModel.addElement(source.toListString());
        }
        listAvailableScripts.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrolChosen = new javax.swing.JScrollPane();
        listChosenScripts = new javax.swing.JList();
        addButton = new javax.swing.JButton();
        scrollAvailable = new javax.swing.JScrollPane();
        listAvailableScripts = new javax.swing.JList();
        removeButton = new javax.swing.JButton();
        battleButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));

        listChosenScripts.setMaximumSize(new java.awt.Dimension(40, 80));
        listChosenScripts.setMinimumSize(new java.awt.Dimension(40, 80));
        scrolChosen.setViewportView(listChosenScripts);

        addButton.setBackground(new java.awt.Color(102, 255, 102));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        listAvailableScripts.setMaximumSize(new java.awt.Dimension(40, 80));
        listAvailableScripts.setMinimumSize(new java.awt.Dimension(40, 80));
        scrollAvailable.setViewportView(listAvailableScripts);

        removeButton.setBackground(new java.awt.Color(255, 51, 51));
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        battleButton.setBackground(new java.awt.Color(153, 153, 255));
        battleButton.setText("Battle");
        battleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Available AI scripts");

        jLabel2.setText("Selected AI scripts");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Select scripts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(battleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(scrolChosen, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrolChosen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(battleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollAvailable))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        for (int index : listAvailableScripts.getSelectedIndices()) {
            if (addedSourceList.size() > VisualConstants.MAX_TANK_NUMBER) {
                ConsoleFrame.showError("Can't add more than " + VisualConstants.MAX_TANK_NUMBER + " tanks");
                break;
            }
            addedSourceList.add(sourceList.get(index));
            addedListModel.addElement(listModel.get(index));
        }
        listChosenScripts.setModel(addedListModel);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        List<Object> listaAux = new ArrayList<>();
        List<Source> listaAux2 = new ArrayList<>();
        for (int index : listChosenScripts.getSelectedIndices()) {
            listaAux.add(addedListModel.get(index));
            listaAux2.add(addedSourceList.get(index));
        }
        for (Object aux : listaAux) {
            addedListModel.removeElement(aux);
        }
        for (Source auxSource : listaAux2) {
            addedSourceList.remove(auxSource);
        }
        listChosenScripts.setModel(addedListModel);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void battleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleButtonActionPerformed
        if (this.listChosenScripts.getModel().getSize() >= 2) {

            VisualEngine visualEngine = VisualEngine.getInstance(addedSourceList);
            visualEngine.setMatchMode(GameModes.SINGLEPLAYER);
            visualEngine.setVisible(true);
        }
    }//GEN-LAST:event_battleButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        rootFrame.changePanel(new MainMenuPanel(rootFrame));
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton battleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList listAvailableScripts;
    private javax.swing.JList listChosenScripts;
    private javax.swing.JButton removeButton;
    private javax.swing.JScrollPane scrolChosen;
    private javax.swing.JScrollPane scrollAvailable;
    // End of variables declaration//GEN-END:variables
}
